from typing import List, Union

import matplotlib
import numpy as np

def figure_to_image(figures:Union[matplotlib.figure.Figure, List[matplotlib.figure.Figure]], close: bool = ...) -> np.ndarray: ...
def make_grid(I:np.ndarray, ncols: int = ...) -> np.ndarray: ...
def convert_to_HWC(tensor:np.ndarray, input_format:str): ...
